source 'https://github.com/CocoaPods/Specs.git'

target 'FPGSilentLogger_Example', :exclusive => true do
  pod "FPGSilentLogger", :path => "../"
end

target 'FPGSilentLogger_Tests', :exclusive => true do
  pod "FPGSilentLogger", :path => "../"
  
end
